name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: 'dipankarmedhi' # Hashnode Username
          COUNT: 4 # MAX Visisble
          STYLE: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
